# Generated by Django 4.0.5 on 2022-06-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='edumaterial',
            name='summary',
            field=models.TextField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='edumaterial',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
