# Generated by Django 4.0.5 on 2022-06-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_edumaterial_pdf_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edumaterial',
            name='pdf_file_content',
        ),
    ]
